import RayleighKernel

/-! This is a reproducible release-surface name/signature and axiom audit.
    Expected axioms are only `propext`, `Classical.choice`, and `Quot.sound`;
    definitions may report no axioms. -/

#check RayleighKernel.Analysis.HalfLineH1.mainOptimizerTheorem
#check RayleighKernel.Claims.mainOptimizer
#check RayleighKernel.Discrete.tendsto_scaledDiscreteMinimum
#check RayleighKernel.Discrete.tendsto_scaled_rayleighQuotient_of_nearMinimizer

#check RayleighKernel.Probability.IsFiniteZeroSum
#check RayleighKernel.Probability.dense_finiteZeroSum
#check RayleighKernel.Probability.DifferenceProjectionIsotropicWhite
#check RayleighKernel.Probability.DifferenceProjectionIsotropicWhite.projection_integral_abs_of_difference
#check RayleighKernel.Probability.turnoverIsotropicWhite_of_difference_projection

#check RayleighKernel.Numerics.tStar_mem_rootBracket
#check RayleighKernel.Numerics.AStar_mem_roundingBin
#check RayleighKernel.Numerics.CStar_mem_roundingBin
#check RayleighKernel.Numerics.kappaStar_mem_roundingBin
#check RayleighKernel.Numerics.lambdaStar_mem_roundingBin
#check RayleighKernel.Numerics.optimizer_ema2_objective_ratio_mem_roundingBin
#check RayleighKernel.Numerics.optimizer_ema2_objective_reduction_percent_mem_roundingBin
#check RayleighKernel.Numerics.optimizer_ema2_turnover_reduction_percent_mem_roundingBin

#check RayleighKernel.Analysis.normalizeMass_isAdmissible
#check RayleighKernel.Analysis.rayleighQuotient_normalizeMass
#check RayleighKernel.Analysis.isMinimizer_normalizeMass_of_isHomogeneousMinimizer
#check RayleighKernel.Analysis.isHomogeneousMinimizer_iff_normalizeMass_isMinimizer
#check RayleighKernel.Analysis.exists_centeredCorrectionBump
#check RayleighKernel.Analysis.HalfLineH1.balance_from_centered_bridge
#check RayleighKernel.Analysis.HalfLineH1.CorrectionBumps.massMultiplier_add_momentMultiplier_mul_eq_zero
#check RayleighKernel.Analysis.CenteredCorrectionBump.exists_pos_homogeneousCentered_correctedVariation
#check RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_nonneg
#check RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_forcing
#check RayleighKernel.Analysis.HalfLineH1.rayleighQuotient_smul
#check RayleighKernel.Analysis.HalfLineH1.firstVariation_eq_zero_of_eventually_slope_nonneg
#check RayleighKernel.Analysis.CenteredCorrectionBump.exists_twoSided_homogeneousCentered_correctedVariation
#check RayleighKernel.Analysis.CenteredCorrectionBump.multiplier_eq_of_isMinimizer
#check RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_eq_correctionBumps
#check RayleighKernel.Analysis.CenteredCorrectionBump.integral_correctionBumps_reactionMeasure_forcing
#check RayleighKernel.Analysis.integral_affine_forcing_mul_schwartz

#print axioms RayleighKernel.Analysis.HalfLineH1.mainOptimizerTheorem
#print axioms RayleighKernel.Claims.mainOptimizer
#print axioms RayleighKernel.Discrete.tendsto_scaledDiscreteMinimum
#print axioms RayleighKernel.Discrete.tendsto_scaled_rayleighQuotient_of_nearMinimizer
#print axioms RayleighKernel.Probability.IsFiniteZeroSum
#print axioms RayleighKernel.Probability.dense_finiteZeroSum
#print axioms RayleighKernel.Probability.DifferenceProjectionIsotropicWhite
#print axioms RayleighKernel.Probability.DifferenceProjectionIsotropicWhite.projection_integral_abs_of_difference
#print axioms RayleighKernel.Probability.turnoverIsotropicWhite_of_difference_projection
#print axioms RayleighKernel.Numerics.tStar_mem_rootBracket
#print axioms RayleighKernel.Numerics.AStar_mem_roundingBin
#print axioms RayleighKernel.Numerics.CStar_mem_roundingBin
#print axioms RayleighKernel.Numerics.kappaStar_mem_roundingBin
#print axioms RayleighKernel.Numerics.lambdaStar_mem_roundingBin
#print axioms RayleighKernel.Numerics.optimizer_ema2_objective_ratio_mem_roundingBin
#print axioms RayleighKernel.Numerics.optimizer_ema2_objective_reduction_percent_mem_roundingBin
#print axioms RayleighKernel.Numerics.optimizer_ema2_turnover_reduction_percent_mem_roundingBin
#print axioms RayleighKernel.Analysis.normalizeMass_isAdmissible
#print axioms RayleighKernel.Analysis.rayleighQuotient_normalizeMass
#print axioms RayleighKernel.Analysis.isMinimizer_normalizeMass_of_isHomogeneousMinimizer
#print axioms RayleighKernel.Analysis.isHomogeneousMinimizer_iff_normalizeMass_isMinimizer
#print axioms RayleighKernel.Analysis.exists_centeredCorrectionBump
#print axioms RayleighKernel.Analysis.HalfLineH1.balance_from_centered_bridge
#print axioms RayleighKernel.Analysis.HalfLineH1.CorrectionBumps.massMultiplier_add_momentMultiplier_mul_eq_zero
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.exists_pos_homogeneousCentered_correctedVariation
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_nonneg
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_forcing
#print axioms RayleighKernel.Analysis.HalfLineH1.rayleighQuotient_smul
#print axioms RayleighKernel.Analysis.HalfLineH1.firstVariation_eq_zero_of_eventually_slope_nonneg
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.exists_twoSided_homogeneousCentered_correctedVariation
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.multiplier_eq_of_isMinimizer
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.correctedFirstVariation_eq_correctionBumps
#print axioms RayleighKernel.Analysis.CenteredCorrectionBump.integral_correctionBumps_reactionMeasure_forcing
#print axioms RayleighKernel.Analysis.integral_affine_forcing_mul_schwartz
